### ISSUE TITLE
Link to Clearpath Robotics Resource Page leads to Page Not Found

### ISSUE THREAD

**Issue by LukaTri** [dingo-cpr/dingo-user-manual#1]
Under README.md, the link under the text "Clearpath Robotics Resource Page" (https://clearpathrobotics.com/dingo-user-manual/) leads to a page not found.

**Comment by tonybaltovski** [comment]
The user manual has moved to: https://docs.clearpathrobotics.com/docs/robots/indoor_robots/dingo/user_manual_dingo/
